# Generated by Django 4.2 on 2023-05-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='temp',
            field=models.CharField(choices=[('Hot', 'H'), ('Cold', 'C')], default='H', max_length=4),
        ),
    ]
