# Generated by Django 4.2 on 2023-05-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_sandwich_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='temp',
            field=models.CharField(choices=[('Hot', 'Hot'), ('Cold', 'Cold')], default='Hot', max_length=4),
        ),
    ]
