# Generated by Django 4.2 on 2023-05-04 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_sandwich_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('sandwich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.sandwich')),
            ],
        ),
    ]
